# Site settings
title: Neil Spurgeon
email: neil@neilspurgeon.com
description: > # this means to ignore newlines until "baseurl:"
  Web designer and developer located in San Luis Obispo, California.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "/" # the base hostname & protocol for your site
github_username:  neilspurgeon

# Build settings
markdown: kramdown
